// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscTransfer is the golang structure for table fa_bsc_transfer.
type FaBscTransfer internal.FaBscTransfer

// Fill with you ideas below.
