// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscGameInfo is the golang structure for table fa_bsc_game_info.
type FaBscGameInfo internal.FaBscGameInfo

// Fill with you ideas below.