// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscUser is the golang structure for table fa_bsc_user.
type FaBscUser internal.FaBscUser

// Fill with you ideas below.
type UserRegisterReq struct {
	UserAddr string `v:"required#请输入用户地址"`
	RefAddr  string
}

type UserInfo struct {
	*FaBscUser
	ReferReward float64 //累计推荐奖励
}

//会员收益排行
type UserReward struct {
	Rank        int     //排名
	Address     string  `orm:"address"      json:"address"`     // 用户地址
	TotalCredit float64 `orm:"total_credit" json:"totalCredit"` // 累计奖励
}

//会员收益排行列表
type UserRewardTop struct {
	List []*UserReward
	ListOutPut
}

//会员记录查询条件
type UserInfoRep struct {
	PageReq
	UserAddr string //钱包地址
	UserId   int
}

//转账信息
type TransferInfo struct {
	FaBscTransfer
	TransferType int //转账类型:1-入,2-出
}

//会员转账列表
type UserTransferList struct {
	List []*TransferInfo
	ListOutPut
}

//会员门票兑换记录
type UserTickerList struct {
	List    []*FaBscUserTicket
	TimeStr string //格式化时间
	ListOutPut
}

//团队会员信息
type TeamUserInfo struct {
	Id      int     `orm:"id,primary"   json:"id"`
	Address string  `orm:"address"      json:"address"` // 用户地址
	Created int     `orm:"created"      json:"created"` // 注册时间
	Num     float64 //兑换粮草消耗USDT
}

//团队会员信息列表
type TeamUserList struct {
	List []*TeamUserInfo
	ListOutPut
}

type UserGameInfo struct {
	*FaBscUserGame
	ImgPath     string  //马匹图片
	Percent     int     //回报进度
	TotalReward float64 //累计收益
}

//会员推荐奖统计
type UserRefRewardInfo struct {
	Month       string  //月份
	TotalReward float64 //推荐收益
}

//扇形图比例分布
type TokenAllocationInfo struct {
	Name    string  //名称
	Percent float64 //比例
}
