// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscTask is the golang structure for table fa_bsc_task.
type FaBscTask internal.FaBscTask

// Fill with you ideas below.