// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscUserGame is the golang structure for table fa_bsc_user_game.
type FaBscUserGame internal.FaBscUserGame

// Fill with you ideas below.