// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscCredit is the golang structure for table fa_bsc_credit.
type FaBscCredit internal.FaBscCredit

// Fill with you ideas below.