// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscListenLog is the golang structure for table fa_bsc_listen_log.
type FaBscListenLog internal.FaBscListenLog

// Fill with you ideas below.
