// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscBaseInfo is the golang structure for table fa_bsc_base_info.
type FaBscBaseInfo internal.FaBscBaseInfo

// Fill with you ideas below.
