// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaBscUserTicket is the golang structure for table fa_bsc_user_ticket.
type FaBscUserTicket internal.FaBscUserTicket

// Fill with you ideas below.