// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"BscDapp/app/model/internal"
)

// FaConfig is the golang structure for table fa_config.
type FaConfig internal.FaConfig

// Fill with you ideas below.
