// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// FaBscListenLog is the golang structure for table fa_bsc_listen_log.
type FaBscListenLog struct {
	Id      int    `orm:"id,primary" json:"id"`      //
	Type    string `orm:"type"       json:"type"`    // 监听类型
	Data    string `orm:"data"       json:"data"`    // 获取内容
	Status  int    `orm:"status"     json:"status"`  // 状态:0-待处理,1-已处理,2-已失败
	Remark  string `orm:"remark"     json:"remark"`  // 备注
	Created int    `orm:"created"    json:"created"` //
}
