// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// FaBscUser is the golang structure for table fa_bsc_user.
type FaBscUser struct {
	Id          int     `orm:"id,primary"   json:"id"`          //
	Address     string  `orm:"address"      json:"address"`     // 用户地址
	RefId       int     `orm:"ref_id"       json:"refId"`       // 推荐人ID
	RefStr      string  `orm:"ref_str"      json:"refStr"`      // 推荐路径
	RefNum      int     `orm:"ref_num"      json:"refNum"`      // 直推人数
	TeamNum     int     `orm:"team_num"     json:"teamNum"`     // 团队人数
	TicketNum   float64 `orm:"ticket_num"   json:"ticketNum"`   // 兑换的门票数
	InvestNum   float64 `orm:"invest_num"   json:"investNum"`   // 投资金额
	PoolCredit  float64 `orm:"pool_credit"  json:"poolCredit"`  // 奖池奖励
	RefCredit   float64 `orm:"ref_credit"   json:"refCredit"`   // 推荐奖励
	Credit      float64 `orm:"credit"       json:"credit"`      // 回报奖励
	TotalCredit float64 `orm:"total_credit" json:"totalCredit"` // 累计奖励
	Created     int     `orm:"created"      json:"created"`     // 注册时间
	Updated     int     `orm:"updated"      json:"updated"`     //
}
