// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// FaBscBaseInfo is the golang structure for table fa_bsc_base_info.
type FaBscBaseInfo struct {
	Id       int    `orm:"id,primary" json:"id"`       //
	TheKey   string `orm:"theKey"     json:"theKey"`   //
	TheValue string `orm:"theValue"   json:"theValue"` //
	Remark   string `orm:"remark"     json:"remark"`   //
	Created  int    `orm:"created"    json:"created"`  //
	Updated  int    `orm:"updated"    json:"updated"`  //
}
