// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// FaBscUserGame is the golang structure for table fa_bsc_user_game.
type FaBscUserGame struct {
    Id        int     `orm:"id,primary" json:"id"`        //           
    Uid       int     `orm:"uid"        json:"uid"`       // 会员ID    
    GameId    int     `orm:"game_id"    json:"gameId"`    // 场次ID    
    InvestNum float64 `orm:"invest_num" json:"investNum"` // 投资金额  
    TicketNum float64 `orm:"ticket_num" json:"ticketNum"` // 门票金额  
    AwardNum  float64 `orm:"award_num"  json:"awardNum"`  // 奖励金额  
    Created   int     `orm:"created"    json:"created"`   //           
}