// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// FaBscGameInfo is the golang structure for table fa_bsc_game_info.
type FaBscGameInfo struct {
    Id       int     `orm:"id,primary" json:"id"`       //                         
    Round    int     `orm:"round"      json:"round"`    // 场次                    
    SeedPool float64 `orm:"seed_pool"  json:"seedPool"` // 种子池                  
    JackPool float64 `orm:"jack_pool"  json:"jackPool"` // 奖金池                  
    EndTime  int     `orm:"end_time"   json:"endTime"`  // 结束时间                
    Status   int     `orm:"status"     json:"status"`   // 状态-1:进行中,2:已结束  
    Updated  int     `orm:"updated"    json:"updated"`  //                         
    Created  int     `orm:"created"    json:"created"`  //                         
}