// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// FaBscUserTicket is the golang structure for table fa_bsc_user_ticket.
type FaBscUserTicket struct {
    Id        int     `orm:"id,primary" json:"id"`        //           
    Uid       int     `orm:"uid"        json:"uid"`       // 会员ID    
    PayNum    float64 `orm:"pay_num"    json:"payNum"`    // 支付数量  
    TicketNum float64 `orm:"ticket_num" json:"ticketNum"` // 门票数量  
    Percent   float64 `orm:"percent"    json:"percent"`   // 兑换比例  
    Created   int     `orm:"created"    json:"created"`   //           
}