// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// FaConfig is the golang structure for table fa_config.
type FaConfig struct {
	Id      uint   `orm:"id,primary"  json:"id"`      //
	Name    string `orm:"name,unique" json:"name"`    // 变量名
	Group   string `orm:"group"       json:"group"`   // 分组
	Title   string `orm:"title"       json:"title"`   // 变量标题
	Tip     string `orm:"tip"         json:"tip"`     // 变量描述
	Type    string `orm:"type"        json:"type"`    // 类型:string,text,int,bool,array,datetime,date,file
	Value   string `orm:"value"       json:"value"`   // 变量值
	Content string `orm:"content"     json:"content"` // 变量字典数据
	Rule    string `orm:"rule"        json:"rule"`    // 验证规则
	Extend  string `orm:"extend"      json:"extend"`  // 扩展属性
	Setting string `orm:"setting"     json:"setting"` // 配置
}
