server:
  Url: "http://127.0.0.1"
  Address: ":8599"
  ServerRoot: "public"
  ServerAgent: "BscDApp"
  LogPath: "log/"
  ClientMaxBodySize: "20m"

logger:
  Path: "log/"
  Level: "all"
  Stdout: true

database:
  link: "mysql:bscDapp:C357TnWe86GWdYfy@tcp(118.89.66.195:3306)/bscdapp"
  maxIdle: "10"
  maxOpen: "100"
  maxLifetime: "30s"
  debug: true
  logger:
    Path: "log/"
    Level: "all"
    Stdout: true

redis:
  default: "127.0.0.1:6379,0"

gfcli:
  gen:
    dao:
      link: "mysql:bscDapp:C357TnWe86GWdYfy@tcp(118.89.66.195:3306)/bscdapp"



