// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscBaseInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscBaseInfoDao struct {
	internal.FaBscBaseInfoDao
}

var (
	// FaBscBaseInfo is globally public accessible object for table fa_bsc_base_info operations.
	FaBscBaseInfo = faBscBaseInfoDao{
		internal.FaBscBaseInfo,
	}
)

// Fill with you ideas below.
