// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscUserGameDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscUserGameDao struct {
	internal.FaBscUserGameDao
}

var (
	// FaBscUserGame is globally public accessible object for table fa_bsc_user_game operations.
	FaBscUserGame = faBscUserGameDao{
		internal.FaBscUserGame,
	}
)

// Fill with you ideas below.