// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscUserDao struct {
	internal.FaBscUserDao
}

var (
	// FaBscUser is globally public accessible object for table fa_bsc_user operations.
	FaBscUser = faBscUserDao{
		internal.FaBscUser,
	}
)

// Fill with you ideas below.