// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscGameInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscGameInfoDao struct {
	internal.FaBscGameInfoDao
}

var (
	// FaBscGameInfo is globally public accessible object for table fa_bsc_game_info operations.
	FaBscGameInfo = faBscGameInfoDao{
		internal.FaBscGameInfo,
	}
)

// Fill with you ideas below.