// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscUserTicketDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscUserTicketDao struct {
	internal.FaBscUserTicketDao
}

var (
	// FaBscUserTicket is globally public accessible object for table fa_bsc_user_ticket operations.
	FaBscUserTicket = faBscUserTicketDao{
		internal.FaBscUserTicket,
	}
)

// Fill with you ideas below.