// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscCreditDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscCreditDao struct {
	internal.FaBscCreditDao
}

var (
	// FaBscCredit is globally public accessible object for table fa_bsc_credit operations.
	FaBscCredit = faBscCreditDao{
		internal.FaBscCredit,
	}
)

// Fill with you ideas below.