// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscListenLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscListenLogDao struct {
	internal.FaBscListenLogDao
}

var (
	// FaBscListenLog is globally public accessible object for table fa_bsc_listen_log operations.
	FaBscListenLog = faBscListenLogDao{
		internal.FaBscListenLog,
	}
)

// Fill with you ideas below.
