// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"BscDapp/app/dao/internal"
)

// faBscTransferDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type faBscTransferDao struct {
	internal.FaBscTransferDao
}

var (
	// FaBscTransfer is globally public accessible object for table fa_bsc_transfer operations.
	FaBscTransfer = faBscTransferDao{
		internal.FaBscTransfer,
	}
)

// Fill with you ideas below.
